### ISSUE TITLE
[Paper Suggestion] NDN

### ISSUE THREAD

**Issue by agawande** [papers-we-love/portland#12]
Paper Suggestion
------------------------

* Title: Named Data Networking
* Link: https://dl.acm.org/doi/pdf/10.1145/2656877.2656887
* Link: https://named-data.net/publications/named_data_networking_ccr/
* Code: https://github.com/named-data/mini-ndn
* Video: https://youtu.be/48VUoBh8gMM

Content Summary
------------------------
Named Data Networking (NDN) is one of five projects funded by the U.S. National Science Foundation under its Future
Internet Architecture Program. NDN has its roots in an earlier project, Content-Centric Networking (CCN), which
Van Jacobson first publicly presented in 2006. The NDN project investigates Jacobson’s proposed evolution from to-
day’s host-centric network architecture (IP) to a data-centric network architecture (NDN). This conceptually simple shift
has far-reaching implications for how we design, develop, deploy, and use networks and applications. We describe the
motivation and vision of this new architecture, and its basic components and operations. We also provide a snapshot of
its current design, development status, and research challenges. More information about the project, including pro-
totype implementations, publications, and annual reports, is available on named-data.net.

**Comment by jdavisp3** [comment]
Thanks @agawande !

**Comment by jdavisp3** [comment]
We plan to read this at our next meeting, still being planned.

**Comment by jdavisp3** [comment]
Read and discussed!
